# Automates running symbolic.py to generate a 
# dataset documentation file and commit it back 
# to the repo and push. This is run after 
# a PR is merged so that the datasets file has 
# the updated datasets documentation.

name: automate

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  generate-dataset:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ssh-key:
            ${{secrets.DEPLOY_ACTION_SECRET}}
      #----------------------------------------------
      #       set up python
      #----------------------------------------------
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      #----------------------------------------------
      #      install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
      #----------------------------------------------
      #         automates updating datasets
      #----------------------------------------------
      - name: Run symbolic.py to update datasets file
        run: |
          poetry run python censusdis/symbolic.py datasets.py
      #----------------------------------------------
      #           commit updated datasets
      #----------------------------------------------
      - name: Commit newly generated datasets file
        run: |
          /usr/bin/git config --local user.email "action@github.com"
          /usr/bin/git config --local user.name "GitHub Action"
          /usr/bin/git add censusdis/datasets.py
          /usr/bin/git diff --staged --quiet || /usr/bin/git commit -m "Update datasets [github action]"
      - name: Update git
        run: |
          git push -f
